# Dockerfile for go-gin-project
# This Dockerfile is used to build a Docker image for go-gin-project.
FROM centos:latest

# Maintainer information for the image
MAINTAINER xiebing <xiebing@xxx.com>

# Labels for the image to provide additional information
LABEL maintainer="xiebing <xiebing@xxx.com>"

# Copy the binary file to the image
COPY --chown=work output/ /home/work/

# Set the working directory to /home/work/
WORKDIR /home/work

# Run the binary file when the container starts
CMD ["bin/go_gin_project"]