# Dockerfile for go-gin-project
# This Dockerfile is used to build a Docker image for go-gin-project.
FROM centos:latest

# Labels for the image to provide additional information
LABEL maintainer="xiebing <xiebing@xxx.com>"
LABEL description="Go Gin Project Docker Image"
LABEL version="1.0"

# Copy the binary file to the image
COPY --chown=work output/ /home/work/

# Set the working directory to /home/work/
WORKDIR /home/work

# Run the binary file when the container starts
CMD ["bin/go_gin_project"]