[ElasticSearch]
# Elasticsearch configuration
# Elasticsearch address
Address = [
    "http://127.0.0.1:9200"
]

# Elasticsearch authentication
# Elasticsearch username
UserName = "elastic"

# Elasticsearch password
PassWord = "123456"

# Elasticsearch connection pool
MaxIdleConns = 100
MaxIdleConnsPerhost = 10

# Elasticsearch connection timeout
IdleConnTimeout = 90