[ElasticSearch]
# Elasticsearch configuration
# Elasticsearch address
Address = [
    "http://127.0.0.1:8200"
]

# Elasticsearch authentication
# Elasticsearch username
UserName = "superuser"

# Elasticsearch password
PassWord = "1234"

# Elasticsearch connection pool
MaxIdleConns = 100
MaxIdleConnsPerhost = 10

# Elasticsearch connection timeout
IdleConnTimeout = 90