[Etcd]
# etcd 配置
Endpoints = [
    "http://127.0.0.1:2379",
    #    "http://192.168.0.11:2379",
    #    "http://192.168.0.12:2379"
]

# 连接超时时间
# 单位：秒
DialTimeout = 5

# 用户名 (当前 etcd 服务器未启用身份验证，留空)
UserName = ""
# 密码 (当前 etcd 服务器未启用身份验证，留空)
PassWord = ""