[Kafka]
# Kafka 配置
# 集群地址
Brokers = [
    "127.0.0.1:9092",
    #    "kafka2:9092",
    #    "kafka3:9092"
]
# 生产者配置
ProducerTopic = "orders"
# 消费者配置
ConsumerTopic = "order_status"
# 消费者分组
GroupID = "order-processor"
# Kafka 版本
# 需要与 Kafka 集群版本严格匹配
Version = "3.5.1"

# 高级配置
[Advanced]
# 生产者最大重试次数
ProducerMaxRetry = 3
# 消费者会话超时（ms）
ConsumerSessionTimeout = 30000
# 心跳间隔（ms）
HeartbeatInterval = 3000
# 最大处理时间（ms）
MaxProcessingTime = 120000