[Redis]
# Redis server configuration
# Redis server address
Addr = "127.0.0.1:6379"
# Redis password (must match Docker container password)
Password = "123456"
# Redis database number
DB = 0

# Connection pool configuration
# Maximum number of connections in pool
PoolSize = 10
# Minimum number of idle connections
MinIdleConns = 5
# Maximum number of retries when operation fails
MaxRetries = 3

# Timeout configuration (Go duration format)
# Connection timeout
DialTimeout = "10s"
# Read timeout
ReadTimeout = "10s"
# Write timeout
WriteTimeout = "10s"
# Pool timeout (time to wait for connection from pool)
PoolTimeout = "10s"
# Idle connection timeout (0 = no timeout)
IdleTimeout = "5m"
# Maximum connection age (0 = no limit)
MaxConnAge = "0s"
# Idle check frequency (0 = no idle check)
IdleCheckFreq = "1m"
# Health check frequency (0 = no health check)
HealthCheckFreq = "30s"