[Redis]
# redis config
# redis address
Addr = "127.0.0.1:6379"
# redis password
Password = ""
# redis db
DB = 0
# connection pool size
PoolSize = 10
# connection pool min idle conns size
MinIdleConns = 5
# redis max retries when operation fails
MaxRetries = 3
# dial timeout (ms)
DialTimeout = 5000
# read timeout (ms)
ReadTimeout = 3000
# write timeout (ms)
WriteTimeout = 3000