# 此文件定义了当前应用所有 server 的端口信息, 在 servers/start.go 中使用

# HTTPServer 的配置
[HTTPServer]
# 监听端口号
Listen = "0.0.0.0:8080"

# 读 Header + Body 超时时间，ms，可选配置，若不配置，或者为0，将不超时
# 建议：内网API服务可以小一些；外网页面可大一些，避免弱网访问失败
# 若遇到读取 request.Body 失败，和此参数有关
# 请根据实际情况进行调整
ReadTimeout = 1 # 1s

# 写超时时间（从请求读取完开始计算），ms，可选配置
# 应该配置成服务的最大允许时间
# 若使用超时中间件，超时中间件对应的超时时间不应该大于该值
# 若要使用 /debug/pprof 功能，请设置一个大于 30s 的值
# 请根据实际情况进行调整
WriteTimeout = 120 # 120s

# 空闲等待超时时间，ms，可选配置，若为0，会使用 ReadTimeout
# 当设置 keep-alives 开启时(HTTP Server 默认开启)，同一个 tcp 连接，读取下一个请求的等待时间
# 若 client 出现 connection reset by peer，可能和此参数有关
# 请根据实际情况进行调整
IdleTimeout = 3 # 3s

# 提供应用的管理、分析类功能
# 如 /debug/pprof/、/debug/panel/、/metrics
# 此端口一般只在内网使用
[AdminServer]
# 监听一个独立的端口号
Listen = "0.0.0.0:8081"

# 版本信息
[Version]
# 版本号
Version = "1.0.0"

# 服务器选项配置
[Options]
# Gin模式: debug, release, test
# debug: 开发模式，输出详细日志
# release: 生产模式，性能优化
# test: 测试模式，用于单元测试
Mode = "release"

# 是否启用pprof性能分析
# 启用后，可访问 /debug/pprof/
# 用于查看程序的性能数据
EnablePprof = false

# 是否启用Prometheus监控指标
# 启用后，可访问 /metrics
EnableMetrics = true

# 信任的代理IP地址列表
# 用于正确获取客户端真实IP地址
TrustedProxies = ["127.0.0.1", "::1"]

# 是否启用CORS跨域资源共享
# 允许前端应用从不同域名访问API
EnableCORS = true

# 是否启用安全头部
# 包括XSS保护、内容类型保护、点击劫持保护等
EnableSecurity = true

# 认证类型: jwt, casbin
AuthType = "jwt"

# 是否启用认证
EnableAuth = true

# 读取超时时间（秒）
ReadTimeout = 30

# 写入超时时间（秒）
WriteTimeout = 30

# 空闲超时时间（秒）
IdleTimeout = 60

# 关闭超时时间（秒）
ShutdownTimeout = 30

# 限流配置
[Options.RateLimit]
# 是否使用Redis限流
# 适用于多实例部署的场景
EnableRedis = true

# 是否使用内存限流
# 适用于单实例部署或开发环境
EnableMemory = false

# 登录接口限流次数（每分钟）
# 防止暴力破解攻击
LoginLimit = 10

# API接口限流次数（每分钟）
# 防止API滥用
APILimit = 100

# 公共接口限流次数（每分钟）
# 对不需要认证的接口进行限流
PublicLimit = 50

# 开发环境配置示例
# 可以创建 conf/service-dev.toml 用于开发环境
# [Options]
# Mode = "debug"
# EnablePprof = true
# EnableAuth = false
# [Options.RateLimit]
# EnableRedis = false
# EnableMemory = true
# LoginLimit = 100
# APILimit = 1000
# PublicLimit = 500

# 生产环境配置示例
# 可以创建 conf/service-prod.toml 用于生产环境
# [Options]
# Mode = "release"
# EnablePprof = false
# EnableAuth = true
# EnableSecurity = true
# TrustedProxies = ["10.0.0.0/8"]
# [Options.RateLimit]
# EnableRedis = true
# EnableMemory = false
# LoginLimit = 5
# APILimit = 50
# PublicLimit = 20