# 安装执行命令： docker-compose -f docker-compose.yml up -d
# 启动单个服务执行命令： docker-compose up -d servername
# 卸载执行命令： docker-compose -f docker-compose.yml down

version: '3'
services:
  mysql:
    container_name: mysql
    restart: always
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test

  postgresql:
    container_name: postgresql
    restart: always
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: test

  mongodb:
    container_name: mongodb
    restart: always
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: test

  clickhouse:
    container_name: clickhouse
    restart: always
    image: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    environment:
      CLICKHOUSE_USER: root
      CLICKHOUSE_PASSWORD: 123456
      CLICKHOUSE_DB: test
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

  redis:
    container_name: redis
    restart: always
    image: redis
    ports:
      - "6379:6379"
  #    command:
  #      - redis-server --requirepass 123456

  etcd:
    container_name: etcd
    restart: always
    image: bitnami/etcd
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      ETCD_NAME: etcd
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://etcd:2380"
      ETCD_INITIAL_CLUSTER: "etcd=http://etcd:2380"

  nsqlookupd:
    container_name: nsqlookupd
    restart: always
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
  nsqd:
    container_name: nsqd
    restart: always
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
  nsqadmin:
    container_name: nsqadmin
    restart: always
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"

  zookeeper:
    container_name: zookeeper
    restart: always
    image: bitnami/zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka:
    container_name: kafka
    restart: always
    image: bitnami/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_ADVERTISED_HOST_NAME: kafka
      KAFKA_BROKER_ID: 1
    depends_on:
      - zookeeper

  # manticore 默认没有用户密码，需自行创建
  manticore:
    container_name: manticore
    restart: always
    image: manticoresearch/manticore
    ports:
      # mysql 兼容端口
      - "9306:9306"
      # HTTP API 端口
      - "9308:9308"
      # 集群端口
      - "9312:9312"
    volumes:
      # 挂载初始化 SQL
      - ./manticore-init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - EXTRA=1
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
    container_name: elasticsearch
    restart: always
    environment:
      - node.name=es01
      - cluster.name=es-cluster
      - discovery.type=single-node  # 单节点模式（开发环境）
      - bootstrap.memory_lock=true  # 锁定内存，防止 OOM
      - xpack.security.enabled=true  # 开启安全认证（账号密码）
      - ELASTIC_PASSWORD=123456  # elastic 用户的密码
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=123456
    depends_on:
      - elasticsearch
    restart: always